spring:
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations:
        - file:C:\repo\pdx-txt-java\rico_webapp\src\main\resources\static\

reCaptcha:
  v3:
    site-key: 6LfwIOkUAAAAAEwRrWTXRWRq68A3EV-zOi5bbStu
    threshold: 0.5
