/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.matanki_saito.rico;

/**
 * Paradox txt library
 */
public class Library {
    /**
     * Speq
     *
     * @return true
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
