name: ecs test

on:
  push:
    tags:
      - 'app-*.*.*'
  workflow_dispatch:
    inputs:
      info:
        description: 'manual trigger'
        required: false

jobs:
  main-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set version to env
        run: |
          VER=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${VER##app-}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

