name: ecs test

on:
  push:
    tags:
      - 'app-*.*.*'
  workflow_dispatch:
    inputs:
      info:
        description: 'manual trigger'
        required: false

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version to env
        run: |
          VER=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${VER##app-}" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: rico_webapp/rico-task.json
          container-name: rico-app
          image: docker.pkg.github.com/matanki-saito/pdx-txt-java/rico-app:${RELEASE_VERSION}-app

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: rico-sv
          cluster: girls
          wait-for-service-stability: true
