name: call gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: test
        run: ./gradlew test
        #      - name: publish package
        #        run: ./gradlew publish
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  GITHUB_USER_NAME: matanki_saito
      - name: release
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew release -Prelease.useAutomaticVersion=true
