name: publish application

on:
  push:
    branches: [ develop ]

jobs:
  main-job:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: publish application docker to github packages
        run: |
          ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u matanki-saito --password-stdin
          ./gradlew :rico_webapp:docker dockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: matanki.saito
      - name: update version and tagging
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew :rico_webapp:release -Prelease.useAutomaticVersion=true
