name: publish library

on:
  push:
    branches: [ main ]

jobs:
  main-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, '[lib deploy]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: test library
        run: ./gradlew :lib:test
      - name: publish library to github packages
        run: ./gradlew :lib:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: matanki.saito
      - name: update version and tagging
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew :lib:release -Prelease.useAutomaticVersion=true
