name: publish library

on:
  push:
    branches: [ main ]

jobs:
  main-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, '[app deploy]')"
    steps:
      - name: test
        run: echo "test"
