name: publish console

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      info:
        description: 'manual trigger'
        required: false
jobs:
  build-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, '[con build]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: publish application docker to github packages
        run: |
          cd rico_console
          .././gradlew :rico_console:shadow shadowJar
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u matanki-saito --password-stdin
          .././gradlew :rico_console:docker dockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: matanki.saito
      - name: update version and tagging
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew :rico_console:release -Prelease.useAutomaticVersion=true
